### PR TITLE
Create packer.json, Autounattend.xml and Vagrantfiles from text/templates

### PR DESCRIPTION
**Pull request by sneal**
This is a WIP, but its working software. To test drive this PR:
1. Build inductor (requires gox) and ensure it's in your PATH along with packer.
2. Git clone joefitzgerald/packer-windows (use the inductor branch).
3. From packer-windows run: `inductor -skipwindowsupdates windows10 && packer build -only=virtualbox-iso packer.json`
4. $$$

### CODE REVIEW

**Comment by joefitzgerald** [comment]
Is `packer` capable of receiving piped input? If so, it would be totally awesome to be able to do `inductor -skipwindowsupdates windows10 | packer`, right?

**Comment by sneal** [comment]
@joefitzgerald I had the same thought WRT to piping input, but I didn't immediately know the answer so I just went around it. Definitely will look into it though.

**Comment by sneal** [comment]
Window7 and Windows 2012R2 build Vagrant boxes without error.

**Comment by sneal** [comment]
@joefitzgerald Next steps?

**Comment by sneal** [comment]
Since this is > current master, merging...

**Comment by joefitzgerald** [comment]
:+1:

**Pull request merged**
